_NEEDS_EPILOGUE = 7
_LOOP_SIZE = 3
_DEFAULTCHARDELAY = 25
_DEFAULTDELAY = 25
def blink():
    count = 0
    while count < 4:
        DSFN_SWC_FILL(100, 100, 100)
        DSFN_DELAY(200)
        DSFN_SWC_FILL(0, 0, 0)
        DSFN_DELAY(200)
        count = count + 1
DSFN_OLED_CLEAR()
DSFN_OLED_CURSOR(20, 20)
DSFN_OLED_PRINT('Are you using')
DSFN_OLED_CURSOR(20, 35)
DSFN_OLED_PRINT('Windows?')
DSFN_OLED_CURSOR(20, 110)
DSFN_OLED_PRINT('-:No     +:Yes')
DSFN_OLED_UPDATE()
blink()
temp = 0
is_win = _BLOCKING_READKEY == 28
if is_win:
    DSFN_SWC_FILL(0, 128, 0)
    DSFN_KEYDOWN('WINDOWS')
    DSFN_KEYDOWN('R')
    DSFN_KEYUP('R')
    DSFN_KEYUP('WINDOWS')
    DSFN_DELAY(750)
    DSFN_STRINGLN('notepad')
    DSFN_DELAY(750)
else:
    DSFN_OLED_CLEAR()
    DSFN_OLED_CURSOR(0, 50)
    DSFN_OLED_PRINT('Open a text editor')
    DSFN_OLED_CURSOR(0, 65)
    DSFN_OLED_PRINT('Anykey when ready')
    DSFN_OLED_UPDATE()
    temp = _BLOCKING_READKEY
    DSFN_SWC_FILL(0, 128, 0)
DSFN_OLED_CLEAR()
DSFN_OLED_CURSOR(30, 50)
DSFN_OLED_PRINT('Typing...')
DSFN_OLED_UPDATE()
DSFN_STRING('dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla c')
DSFN_STRING('onsequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. ')
DSFN_KEYDOWN('ENTER')
DSFN_KEYUP('ENTER')
DSFN_STRING('dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla c')
DSFN_STRING('onsequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. ')
if is_win:
    DSFN_KEYDOWN('CTRL')
    DSFN_KEYDOWN('+')
    DSFN_KEYUP('+')
    DSFN_KEYUP('CTRL')
    DSFN_KEYDOWN('CTRL')
    DSFN_KEYDOWN('+')
    DSFN_KEYUP('+')
    DSFN_KEYUP('CTRL')
    DSFN_KEYDOWN('CTRL')
    DSFN_KEYDOWN('+')
    DSFN_KEYUP('+')
    DSFN_KEYUP('CTRL')
    DSFN_KEYDOWN('CTRL')
    DSFN_KEYDOWN('+')
    DSFN_KEYUP('+')
    DSFN_KEYUP('CTRL')
    DSFN_KEYDOWN('CTRL')
    DSFN_KEYDOWN('+')
    DSFN_KEYUP('+')
    DSFN_KEYUP('CTRL')
    DSFN_KEYDOWN('WINDOWS')
    DSFN_KEYDOWN('UP')
    DSFN_KEYUP('UP')
    DSFN_KEYUP('WINDOWS')
DSFN_SWC_RESET(99)
if _KEYPRESS_COUNT % _LOOP_SIZE == 0:
    DSFN_STRING('first action')
    DSFN_KEYDOWN('ENTER')
    DSFN_KEYUP('ENTER')
if _KEYPRESS_COUNT % _LOOP_SIZE == 1:
    DSFN_STRING('second action')
    DSFN_KEYDOWN('ENTER')
    DSFN_KEYUP('ENTER')
if _KEYPRESS_COUNT % _LOOP_SIZE == 2:
    DSFN_STRING('third action')
    DSFN_KEYDOWN('ENTER')
    DSFN_KEYUP('ENTER')
    DSFN_KEYDOWN('ALT')
    DSFN_KEYUP('ALT')
    DSFN_STRINGLN('dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.')
    DSFN_STRINGLN('pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. ')
    DSFN_KEYDOWN('OPTION')
    DSFN_KEYUP('OPTION')
    DSFN_KEYDOWN('LMOUSE')
    DSFN_KEYUP('LMOUSE')
    DSFN_KEYDOWN('MMOUSE')
    DSFN_KEYUP('MMOUSE')
