
#ifndef ds_vm_h
#define ds_vm_h

#include <stdint.h>
#include <string.h>

//--------------

#define EXE_BIN_START_ADDRESS 0x0
#define DATA_STACK_START_ADDRESS 0xf800
#define STACK_MOAT_SIZE 32
#define USER_VAR_START_ADDRESS 0xFA00
#define USER_VAR_END_ADDRESS_INCLUSIVE 0xFBFF

#define PGV_COUNT 32
#define PGV_START_ADDRESS 0xFD00
#define PGV_END_ADDRESS_INCLUSIVE 0xFDFF

#define INTERAL_VAR_START_ADDRESS 0xFE00
#define INTERAL_VAR_BYTE_WIDTH 4
#define MEMORY_END 0xFFFF

// ----------
#define BIN_BUF_SIZE 0xffff
// ----------

#define EXE_OK 0

#define EXE_ACTION_SLEEP 1
#define EXE_ACTION_PREV_PROFILE 2
#define EXE_ACTION_NEXT_PROFILE 3
#define EXE_ACTION_GOTO_PROFILE 4

#define EXE_HALT 10
#define EXE_ABORTED 11

#define EXE_ERROR_CODE_START 20
#define EXE_ILLEGAL_INSTRUCTION EXE_ERROR_CODE_START
#define EXE_DSB_INCOMPATIBLE_VERSION (EXE_ERROR_CODE_START + 1)
#define EXE_DSB_FOPEN_FAIL (EXE_ERROR_CODE_START + 2)
#define EXE_DSB_FREAD_ERROR (EXE_ERROR_CODE_START + 3)
#define EXE_STACK_OVERFLOW (EXE_ERROR_CODE_START + 4)
#define EXE_STACK_UNDERFLOW (EXE_ERROR_CODE_START + 5)
#define EXE_DIVISION_BY_ZERO (EXE_ERROR_CODE_START + 6)
#define EXE_ILLEGAL_ADDR (EXE_ERROR_CODE_START + 7)

#define _DEFAULTDELAY (INTERAL_VAR_START_ADDRESS + 0 * INTERAL_VAR_BYTE_WIDTH)
#define _DEFAULTCHARDELAY (INTERAL_VAR_START_ADDRESS + 1 * INTERAL_VAR_BYTE_WIDTH)
#define _CHARJITTER (INTERAL_VAR_START_ADDRESS + 2 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_MIN (INTERAL_VAR_START_ADDRESS + 3 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_MAX (INTERAL_VAR_START_ADDRESS + 4 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_INT (INTERAL_VAR_START_ADDRESS + 5 * INTERAL_VAR_BYTE_WIDTH)
#define _TIME_MS (INTERAL_VAR_START_ADDRESS + 6 * INTERAL_VAR_BYTE_WIDTH)
#define _READKEY (INTERAL_VAR_START_ADDRESS + 7 * INTERAL_VAR_BYTE_WIDTH)
#define _LOOP_SIZE (INTERAL_VAR_START_ADDRESS + 8 * INTERAL_VAR_BYTE_WIDTH)
#define _KEYPRESS_COUNT (INTERAL_VAR_START_ADDRESS + 9 * INTERAL_VAR_BYTE_WIDTH)
#define _NEEDS_EPILOGUE (INTERAL_VAR_START_ADDRESS + 10 * INTERAL_VAR_BYTE_WIDTH)
#define _TIME_S (INTERAL_VAR_START_ADDRESS + 11 * INTERAL_VAR_BYTE_WIDTH)
#define _ALLOW_ABORT (INTERAL_VAR_START_ADDRESS + 12 * INTERAL_VAR_BYTE_WIDTH)
#define _BLOCKING_READKEY (INTERAL_VAR_START_ADDRESS + 13 * INTERAL_VAR_BYTE_WIDTH)
#define _IS_NUMLOCK_ON (INTERAL_VAR_START_ADDRESS + 14 * INTERAL_VAR_BYTE_WIDTH)
#define _IS_CAPSLOCK_ON (INTERAL_VAR_START_ADDRESS + 15 * INTERAL_VAR_BYTE_WIDTH)
#define _IS_SCROLLLOCK_ON (INTERAL_VAR_START_ADDRESS + 16 * INTERAL_VAR_BYTE_WIDTH)
#define _DONT_REPEAT (INTERAL_VAR_START_ADDRESS + 17 * INTERAL_VAR_BYTE_WIDTH)
#define _THIS_KEYID (INTERAL_VAR_START_ADDRESS + 18 * INTERAL_VAR_BYTE_WIDTH)
#define _DP_MODEL (INTERAL_VAR_START_ADDRESS + 19 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_IS_VALID (INTERAL_VAR_START_ADDRESS + 20 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_UTC_OFFSET (INTERAL_VAR_START_ADDRESS + 21 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_YEAR (INTERAL_VAR_START_ADDRESS + 22 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_MONTH (INTERAL_VAR_START_ADDRESS + 23 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_DAY (INTERAL_VAR_START_ADDRESS + 24 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_HOUR (INTERAL_VAR_START_ADDRESS + 25 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_MINUTE (INTERAL_VAR_START_ADDRESS + 26 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_SECOND (INTERAL_VAR_START_ADDRESS + 27 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_WDAY (INTERAL_VAR_START_ADDRESS + 28 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_YDAY (INTERAL_VAR_START_ADDRESS + 29 * INTERAL_VAR_BYTE_WIDTH)
#define _STR_PRINT_FORMAT (INTERAL_VAR_START_ADDRESS + 30 * INTERAL_VAR_BYTE_WIDTH)
#define _STR_PRINT_PADDING (INTERAL_VAR_START_ADDRESS + 31 * INTERAL_VAR_BYTE_WIDTH)
#define _UNUSED (INTERAL_VAR_START_ADDRESS + 32 * INTERAL_VAR_BYTE_WIDTH)

typedef struct
{
  uint8_t result;
  uint16_t next_pc;
  uint8_t data;
  uint8_t epilogue_actions;
} exe_context;

#define DEFAULT_CMD_DELAY_MS 20
#define DEFAULT_CHAR_DELAY_MS 20

#define EPILOGUE_SAVE_LOOP_STATE 0x1
#define EPILOGUE_SAVE_COLOR_STATE 0x2
#define EPILOGUE_NEED_OLED_RESTORE 0x4
#define EPILOGUE_DONT_AUTO_REPEAT 0x8
#define EPILOGUE_SAVE_GV 0x10

#define MAX(a, b) ((a) > (b) ? (a) : (b))

extern uint8_t bin_buf[BIN_BUF_SIZE];
extern uint8_t allow_abort;
extern uint8_t kb_led_status;
extern uint32_t pgv_buf[PGV_COUNT];

extern uint8_t str_print_format;
extern uint8_t str_print_padding;

#define STR_PRINT_FORMAT_DEC_UNSIGNED    0
#define STR_PRINT_FORMAT_DEC_SIGNED      1
#define STR_PRINT_FORMAT_HEX_LOWER_CASE  2
#define STR_PRINT_FORMAT_HEX_UPPER_CASE  3

#define NEOPIXEL_COUNT 20

#define DUMMY_VALUE 69

#endif

